sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - build-essential

script:
  - cargo build --verbose --all
  - cargo test  --verbose --all
